### ISSUE TITLE
PA Review: User Auth

### ISSUE THREAD

**Issue by jeffreychuc** [jeffreychuc/NeverBlank#2]
- [x] User creation
- [x] User login
- [x] User logout
- [x] Frontpage styling
- [x] standalone login page styling
- [x] Demo user login
- [x] Shows login/signup errors
- [x] Protect routes with authroute

todo: 
responsive styling

**Comment by chungkikelly** [comment]
There are no login or sign up errors that pop up at the moment.

**Comment by chungkikelly** [comment]
Styling is good (not completely responsive yet, but it doesn't have to be for this project). Users can be created and demo log is cool. Make sure to ping me when the errors render.

**Comment by jeffreychuc** [comment]
@chungkikelly Error rendering has been fixed.  Also the TypeError crash.

**Comment by chungkikelly** [comment]
Good to go.
