### ISSUE TITLE
PA Review: Notebooks

### ISSUE THREAD

**Issue by jeffreychuc** [jeffreychuc/NeverBlank#6]
- [x] Notebooks can be created
- [x] Notebooks can be deleted
- [x] Notebook notes will be deleted when notebook is deleted.
- [x] Notebook titles can be updated
- [x] Modal for notebook creation
- [x] Notes can be added to a notebook

**Comment by jeffreychuc** [comment]
Notebooks implemented on the backend.

~~- Associated notes will be deleted when notebook is deleted.~~
fixed in df4b6d2c1e190a74f54a618291f3631dac7d2527

~~Notebook deletion implemented on frontend.~~
done in b6f64a8ed32c882c96e454e1dc64209d28516094
~~TODO: modal for notebook creation~~
done in 920f4fe819484c56f508263a48c38eb48f14d2be

**Comment by jeffreychuc** [comment]
notebook title editing done in 
0f093adde77bc7e9a50926b35e42546d6d986404

**Comment by jeffreychuc** [comment]
note saving to notebooks added in 2319034892051f4c43a24963e8aa72cd141cb920

**Comment by jeffreychuc** [comment]
TODO: need to style

**Comment by jeffreychuc** [comment]
New users now have default notebooks that cannot be deleted.
67d7c260b96bbdd0f6ebb89652040d662bebabbb

**Comment by chungkikelly** [comment]
Can't create a notebook right now. It spits out the error `400 Bad Request`

**Comment by jeffreychuc** [comment]
@chungkikelly fixed in ~~d9c8341fba3a94713e922a583d03cd3ca199cfad~~ 93e8b6c354678872914ffc6640b61dd8f22895ef

Currently live on heroku.  neverblank.jchuc.me

TODO: Styling
