### ISSUE TITLE
PA Review: Autosave

### ISSUE THREAD

**Issue by jeffreychuc** [jeffreychuc/NeverBlank#9]
- [x] working autosave

**Comment by chungkikelly** [comment]
Keep in mind that Autosave isn't a MVP of Evernote. I would suggest prioritizing the other MVP features before this one, but nonetheless: dope.

**Comment by chungkikelly** [comment]
I also can't currently navigate anywhere other than your login screen, so ping me when your Heroku's updated.

**Comment by jeffreychuc** [comment]
Currently fixing bug for that, need to handle case of user without any notes.

**Comment by jeffreychuc** [comment]
fully working and on heroku as of now.

**Comment by chungkikelly** [comment]
Autosaving definitely works. One note (no pun intended), your preview of each note seems to cut out all white space, including spaces?

**Comment by jeffreychuc** [comment]
Will look into the preview, should be an easy fix.
